export const copy = {
  en: {
    shop: 'Shop', categories: 'Jewelry', newArrivals: 'New pieces', bestSellers: 'Favorites', necklaces: 'Necklaces', earrings: 'Earrings', bracelets: 'Bracelets', rings: 'Rings', storyNav: 'Our story',
    search: 'Search', cart: 'My selection', account: 'Account', heroEyebrow: 'Handcrafted with soul', heroTitle: 'Oriental inspiration, shaped by hand.', heroBody: "Discover handcrafted jewelry inspired by the warmth, detail and poetry of the Orient. Each Perle d'Orient piece is finished in small series.",
    explore: 'Discover the jewelry', story: 'Meet the artisan', featured: 'Signature pieces', discover: 'Jewelry made to be remembered.', addToCart: 'Add to my selection', outOfStock: 'Unavailable', lowStock: 'Only a few left', inStock: 'Available', viewAll: 'View all jewelry',
    newsletterTitle: 'Need a personal recommendation?', newsletterBody: 'Write to us on WhatsApp for sizing, materials, gifts and availability.', subscribe: 'Chat on WhatsApp', trustDelivery: 'Delivery in Morocco & worldwide', trustPayment: 'Order on WhatsApp', trustSupport: 'Direct artisan assistance',
    catalogue: 'The collection', results: 'pieces', filters: 'Filters', availability: 'Available only', allCategories: 'All jewelry', subtotal: 'Selection total', delivery: 'Delivery', total: 'Estimated total', checkout: 'Order on WhatsApp', continueShopping: 'Continue discovering', emptyCart: 'Your selection is waiting for its first piece.',
    checkoutTitle: 'Your WhatsApp order', orderSummary: 'Your selection', placeOrder: 'Continue to WhatsApp', firstName: 'First name', lastName: 'Last name', telephone: 'Telephone', email: 'Email (optional)', city: 'City', address: 'Delivery address', notes: 'Message or gift note (optional)', cod: 'Cash on delivery', whatsapp: 'WhatsApp order', consent: 'I accept the terms and delivery policy.', confirmationTitle: 'Your selection is ready.', confirmationBody: 'Continue on WhatsApp to confirm availability and delivery.', orderNumber: 'Reference',
  },
  fr: {
    shop: 'Boutique', categories: 'Bijoux', newArrivals: 'Nouveautés', bestSellers: 'Coups de cœur', necklaces: 'Colliers', earrings: "Boucles d'oreilles", bracelets: 'Bracelets', rings: 'Bagues', storyNav: 'Notre histoire',
    search: 'Rechercher', cart: 'Ma sélection', account: 'Compte', heroEyebrow: 'Façonné avec âme', heroTitle: "Un souffle d'Orient, façonné à la main.", heroBody: "Découvrez des bijoux artisanaux inspirés par la chaleur, les détails et la poésie de l'Orient. Chaque pièce Perle d'Orient est réalisée en petite série.",
    explore: 'Découvrir les bijoux', story: "Rencontrer l'artisane", featured: 'Pièces signature', discover: 'Des bijoux créés pour laisser une empreinte.', addToCart: 'Ajouter à ma sélection', outOfStock: 'Indisponible', lowStock: 'Plus que quelques pièces', inStock: 'Disponible', viewAll: 'Voir tous les bijoux',
    newsletterTitle: "Besoin d'un conseil personnalisé ?", newsletterBody: 'Écrivez-nous sur WhatsApp pour les tailles, matières, cadeaux et disponibilités.', subscribe: 'Discuter sur WhatsApp', trustDelivery: 'Livraison au Maroc et à l’international', trustPayment: 'Commande via WhatsApp', trustSupport: "Conseil direct de l'artisane",
    catalogue: 'La collection', results: 'pièces', filters: 'Filtres', availability: 'Disponibles uniquement', allCategories: 'Tous les bijoux', subtotal: 'Total de la sélection', delivery: 'Livraison', total: 'Total estimé', checkout: 'Commander sur WhatsApp', continueShopping: 'Continuer à découvrir', emptyCart: 'Votre sélection attend sa première pièce.',
    checkoutTitle: 'Votre commande WhatsApp', orderSummary: 'Votre sélection', placeOrder: 'Continuer sur WhatsApp', firstName: 'Prénom', lastName: 'Nom', telephone: 'Téléphone', email: 'E-mail (facultatif)', city: 'Ville', address: 'Adresse de livraison', notes: 'Message ou note cadeau (facultatif)', cod: 'Paiement à la livraison', whatsapp: 'Commande WhatsApp', consent: "J'accepte les conditions et la politique de livraison.", confirmationTitle: 'Votre sélection est prête.', confirmationBody: 'Continuez sur WhatsApp pour confirmer la disponibilité et la livraison.', orderNumber: 'Référence',
  },
} as const
