export const copy = {
  ar: {
    shop: 'المتجر', categories: 'المجوهرات', newArrivals: 'وصل حديثاً', bestSellers: 'المفضلة', necklaces: 'القلائد', earrings: 'الأقراط', bracelets: 'الأساور', rings: 'الخواتم', storyNav: 'قصتنا',
    search: 'بحث', cart: 'مختاراتي', account: 'الحساب', heroEyebrow: 'مصنوع بحب', heroTitle: 'نفحة شرقية، صُنعت يدوياً.', heroBody: 'اكتشفي مجوهرات حرفية مستوحاة من دفء الشرق وتفاصيله وشاعريته. تُنجز كل قطعة من Casa de Perla ضمن مجموعات محدودة.',
    explore: 'اكتشفي المجوهرات', story: 'تعرّفي على الحرفية', featured: 'قطع مميزة', discover: 'مجوهرات صُممت لتترك أثراً.', addToCart: 'أضيفي إلى مختاراتي', outOfStock: 'غير متوفر', lowStock: 'بقيت قطع قليلة', inStock: 'متوفر', viewAll: 'شاهدي كل المجوهرات',
    newsletterTitle: 'هل تحتاجين إلى نصيحة شخصية؟', newsletterBody: 'تواصلي معنا عبر واتساب للاستفسار عن المقاسات والخامات والهدايا والتوفر.', subscribe: 'تواصلي عبر واتساب', trustDelivery: 'التوصيل داخل المغرب ودولياً', trustPayment: 'الطلب عبر واتساب', trustSupport: 'مساعدة مباشرة وشخصية',
    catalogue: 'المجموعة', results: 'قطع', filters: 'التصفية', availability: 'المتوفر فقط', allCategories: 'كل المجوهرات', subtotal: 'مجموع المختارات', delivery: 'التوصيل', total: 'المجموع التقديري', checkout: 'الطلب عبر واتساب', continueShopping: 'متابعة التصفح', emptyCart: 'مختاراتك بانتظار أول قطعة.',
    checkoutTitle: 'طلبك عبر واتساب', orderSummary: 'مختاراتك', placeOrder: 'المتابعة إلى واتساب', firstName: 'الاسم الأول', lastName: 'اسم العائلة', telephone: 'الهاتف', email: 'البريد الإلكتروني (اختياري)', city: 'المدينة', address: 'عنوان التوصيل', notes: 'رسالة أو ملاحظة للهدية (اختياري)', cod: 'الدفع عند الاستلام', whatsapp: 'طلب واتساب', consent: 'أوافق على الشروط وسياسة التوصيل.', confirmationTitle: 'مختاراتك جاهزة.', confirmationBody: 'تابعي عبر واتساب لتأكيد التوفر والتوصيل.', orderNumber: 'المرجع',
  },
  fr: {
    shop: 'Boutique', categories: 'Bijoux', newArrivals: 'Nouveautés', bestSellers: 'Coups de cœur', necklaces: 'Colliers', earrings: "Boucles d'oreilles", bracelets: 'Bracelets', rings: 'Bagues', storyNav: 'Notre histoire',
    search: 'Rechercher', cart: 'Ma sélection', account: 'Compte', heroEyebrow: 'Façonné avec âme', heroTitle: "Un souffle d'Orient, façonné à la main.", heroBody: "Découvrez des bijoux artisanaux inspirés par la chaleur, les détails et la poésie de l'Orient. Chaque pièce Casa de Perla est réalisée en petite série.",
    explore: 'Découvrir les bijoux', story: "Rencontrer l'artisane", featured: 'Pièces signature', discover: 'Des bijoux créés pour laisser une empreinte.', addToCart: 'Ajouter à ma sélection', outOfStock: 'Indisponible', lowStock: 'Plus que quelques pièces', inStock: 'Disponible', viewAll: 'Voir tous les bijoux',
    newsletterTitle: "Besoin d'un conseil personnalisé ?", newsletterBody: 'Écrivez-nous sur WhatsApp pour les tailles, matières, cadeaux et disponibilités.', subscribe: 'Discuter sur WhatsApp', trustDelivery: 'Livraison au Maroc et à l’international', trustPayment: 'Commande via WhatsApp', trustSupport: "Conseil direct de l'artisane",
    catalogue: 'La collection', results: 'pièces', filters: 'Filtres', availability: 'Disponibles uniquement', allCategories: 'Tous les bijoux', subtotal: 'Total de la sélection', delivery: 'Livraison', total: 'Total estimé', checkout: 'Commander sur WhatsApp', continueShopping: 'Continuer à découvrir', emptyCart: 'Votre sélection attend sa première pièce.',
    checkoutTitle: 'Votre commande WhatsApp', orderSummary: 'Votre sélection', placeOrder: 'Continuer sur WhatsApp', firstName: 'Prénom', lastName: 'Nom', telephone: 'Téléphone', email: 'E-mail (facultatif)', city: 'Ville', address: 'Adresse de livraison', notes: 'Message ou note cadeau (facultatif)', cod: 'Paiement à la livraison', whatsapp: 'Commande WhatsApp', consent: "J'accepte les conditions et la politique de livraison.", confirmationTitle: 'Votre sélection est prête.', confirmationBody: 'Continuez sur WhatsApp pour confirmer la disponibilité et la livraison.', orderNumber: 'Référence',
  },
} as const
