import { ArrowLeft, Minus, Plus, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { removeCartItem, updateCartQuantity } from '../features/cart/cart'
import { useCart } from '../features/cart/cart-context'
import { useI18n } from '../i18n/i18n'
import { formatMoney } from '../lib/format'

export function CartPage() {
  const { state, dispatch, subtotal } = useCart()
  const { locale, t } = useI18n()
  const progress = Math.min(100, subtotal / 500 * 100)
  if (!state.items.length) return <main className="container-shell grid min-h-[60vh] place-items-center py-20 text-center"><div><p className="eyebrow">Perle d'Orient</p><h1 className="display mt-3 text-5xl font-semibold">{t('emptyCart')}</h1><Link to="/catalogue" className="button-primary mt-8"><ArrowLeft size={16} />{t('continueShopping')}</Link></div></main>
  return <main className="container-shell py-9 lg:py-16"><p className="eyebrow">Your selection</p><h1 className="display mt-2 text-[2.5rem] font-semibold sm:text-5xl">{t('cart')}</h1><div className="mt-7 grid gap-8 lg:mt-10 lg:grid-cols-[1fr_390px] lg:gap-10"><div className="divide-y divide-line border-y border-line">{state.items.map((item) => <article key={item.variantId} className="relative grid grid-cols-[92px_1fr] gap-4 py-5 pr-10 sm:grid-cols-[128px_1fr_auto] sm:pr-0"><img src={item.imageUrl} alt={item.name} className="aspect-square h-full w-full rounded-xl object-cover" /><div><Link to={`/products/${item.slug}`} className="display text-xl font-semibold sm:text-2xl">{item.name}</Link><p className="mt-1 text-xs text-muted">{item.variantName}</p><p className="mt-3 text-sm font-semibold">{formatMoney(item.unitPrice, locale)}</p><div className="mt-4 flex w-fit items-center rounded-xl border border-line bg-white"><button className="grid h-11 w-11 place-items-center" onClick={() => dispatch(updateCartQuantity(item.variantId, item.quantity - 1))}><Minus size={13} /></button><span className="w-8 text-center text-xs font-semibold">{item.quantity}</span><button className="grid h-11 w-11 place-items-center" onClick={() => dispatch(updateCartQuantity(item.variantId, item.quantity + 1))}><Plus size={13} /></button></div></div><button onClick={() => dispatch(removeCartItem(item.variantId))} className="absolute right-0 top-4 grid h-11 w-11 place-items-center rounded-full text-muted transition-colors hover:bg-red-50 hover:text-red-700 sm:static sm:self-start" aria-label={`Remove ${item.name}`}><Trash2 size={17} /></button></article>)}</div>
      <aside className="h-fit rounded-[24px] border border-line bg-[#FFFDFC] p-6 shadow-soft sm:p-7"><h2 className="display text-3xl font-semibold">{t('orderSummary')}</h2><div className="mt-6"><div className="mb-2 flex justify-between gap-4 text-xs text-muted"><span>{subtotal >= 500 ? 'You unlocked free delivery.' : `${formatMoney(500 - subtotal, locale)} until free delivery`}</span><span>{Math.round(progress)}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-line"><div className="h-full bg-accent" style={{ width: `${progress}%` }} /></div></div><dl className="mt-7 space-y-4 border-y border-line py-5 text-sm"><div className="flex justify-between"><dt>{t('subtotal')}</dt><dd className="font-semibold">{formatMoney(subtotal, locale)}</dd></div><div className="flex justify-between"><dt>{t('delivery')}</dt><dd className="text-right font-semibold">{subtotal >= 500 ? 'Complimentary' : 'Calculated at checkout'}</dd></div></dl><Link to="/checkout" className="button-primary mt-6 w-full">{t('checkout')}</Link><Link to="/catalogue" className="mt-5 flex min-h-11 items-center justify-center gap-2 text-[10px] font-bold uppercase tracking-widest"><ArrowLeft size={14} />{t('continueShopping')}</Link></aside>
    </div></main>
}
