import { Check, ChevronDown, ChevronRight, MessageCircle, Minus, Plus, Share2, ShoppingBag } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ProductCard } from '../components/product/ProductCard'
import { ProductImageViewer } from '../components/product/ProductImageViewer'
import { addCartItem, clearCart } from '../features/cart/cart'
import { useCart } from '../features/cart/cart-context'
import { useCatalogProducts } from '../features/catalog/catalog-api'
import { useI18n } from '../i18n/i18n'
import { formatMoney } from '../lib/format'

const pageCopy = {
  ar: { selectFinish: 'اختاري اللمسة النهائية', quantity: 'الكمية', added: 'تمت الإضافة', purchaseLabel: 'تفاصيل شراء القطعة', description: 'الوصف', specifications: 'المواصفات', delivery: 'التوصيل والإرجاع', deliveryBody: 'التوصيل المتوقع خلال يومين إلى 4 أيام عمل. يمكن إرجاع القطع غير المستعملة خلال 7 أيام.', related: 'قد يعجبك أيضاً', relatedTitle: 'واصلي اكتشاف المجموعة.', directOrder: 'اطلبي عبر واتساب', openImage: 'تكبير صورة القطعة', closeImage: 'إغلاق الصورة المكبرة', enlargedImage: 'صورة مكبرة', imageHint: 'تكبير' },
  fr: { selectFinish: 'Choisir la finition', quantity: 'Quantité', added: 'Ajouté', purchaseLabel: "Détails d'achat du produit", description: 'Description', specifications: 'Caractéristiques', delivery: 'Livraison et retours', deliveryBody: 'Livraison estimée sous 2 à 4 jours ouvrés. Les pièces non portées peuvent être retournées sous 7 jours.', related: 'Vous aimerez aussi', relatedTitle: 'Continuez votre découverte.', directOrder: 'Commander via WhatsApp', openImage: 'Agrandir la photo du bijou', closeImage: 'Fermer la photo agrandie', enlargedImage: 'Photo agrandie', imageHint: 'Agrandir' },
} as const

export function ProductPage() {
  const { slug } = useParams()
  const navigate = useNavigate()
  const { locale, t } = useI18n()
  const products = useCatalogProducts(locale)
  const product = products.find((item) => item.slug === slug) ?? products[0]
  const [variantId, setVariantId] = useState(product.variants[0].id)
  const [quantity, setQuantity] = useState(1)
  const [added, setAdded] = useState(false)
  const [shareState, setShareState] = useState<'idle' | 'copied'>('idle')
  const { dispatch } = useCart()
  const copy = pageCopy[locale]
  useEffect(() => { setVariantId(product.variants[0].id); setQuantity(1) }, [product.id, product.variants])
  const variant = useMemo(() => product.variants.find((item) => item.id === variantId) ?? product.variants[0], [product, variantId])
  const selectedCartItem = { productId: product.id, variantId: variant.id, slug: product.slug, name: product.name, variantName: variant.name, imageUrl: variant.image ?? product.image, unitPrice: variant.price, stockQuantity: variant.stock }
  const add = () => { dispatch(addCartItem(selectedCartItem, quantity)); setAdded(true); setTimeout(() => setAdded(false), 1800) }
  const orderDirectly = () => {
    if (variant.stock === 0) return
    dispatch(clearCart())
    dispatch(addCartItem(selectedCartItem, quantity))
    navigate('/checkout')
  }
  const share = async () => {
    const url = window.location.href
    const title = product.name
    const text = `${product.name} - Perle d'Orient`
    if (navigator.share) {
      await navigator.share({ title, text, url })
      return
    }
    await navigator.clipboard.writeText(url)
    setShareState('copied')
    window.setTimeout(() => setShareState('idle'), 1800)
  }
  const shareLabel = shareState === 'copied' ? (locale === 'fr' ? 'Lien copié' : 'تم نسخ الرابط') : (locale === 'fr' ? 'Partager' : 'مشاركة')
  return <main className="bg-white pb-6 md:pb-0"><nav aria-label={locale === 'fr' ? 'Fil d’Ariane' : 'مسار التنقل'} className="container-shell flex items-center gap-2 overflow-hidden py-4 text-[9px] font-semibold uppercase tracking-[.16em] text-muted sm:py-5"><Link to="/catalogue" className="shrink-0 transition-colors hover:text-accent">{locale === 'fr' ? 'Boutique' : 'المتجر'}</Link><ChevronRight className="shrink-0 text-accent" size={11} /><span className="shrink-0">{product.category}</span><ChevronRight className="shrink-0 text-accent" size={11} /><span className="truncate text-ink">{product.name}</span></nav>
    <section className="container-shell grid gap-7 pb-14 lg:grid-cols-[minmax(0,1.08fr)_minmax(380px,.92fr)] lg:items-start lg:gap-10 xl:gap-14"><div className="lg:sticky lg:top-28"><div className="relative aspect-[5/4] overflow-hidden rounded-[22px] border border-line bg-[#F5F2ED] shadow-[0_20px_60px_rgba(47,42,44,.08)] sm:rounded-[28px]"><ProductImageViewer src={variant.image ?? product.image} alt={product.name} openLabel={copy.openImage} closeLabel={copy.closeImage} dialogLabel={`${copy.enlargedImage} : ${product.name}`} enlargedAlt={`${product.name} — ${copy.enlargedImage}`} hint={copy.imageHint} /><span className="pointer-events-none absolute bottom-4 left-4 z-20 rounded-full border border-white/55 bg-white/90 px-3 py-1.5 text-[9px] font-bold uppercase tracking-[.14em] text-ink shadow-sm backdrop-blur sm:bottom-5 sm:left-5">{variant.stock > 0 ? t('inStock') : t('outOfStock')}</span></div></div><aside aria-label={copy.purchaseLabel} className="overflow-hidden rounded-[24px] border border-line bg-white p-5 shadow-[0_22px_70px_rgba(47,42,44,.07)] sm:rounded-[28px] sm:p-8 lg:p-9"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="eyebrow">{product.brand}</p><h1 className="display mt-3 text-[2.35rem] font-semibold leading-[1.02] text-ink sm:text-5xl">{product.name}</h1></div><button type="button" onClick={share} className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-line bg-white text-ink transition hover:border-accent hover:text-accent" aria-label={shareLabel} title={shareLabel}>{shareState === 'copied' ? <Check size={17} /> : <Share2 size={17} />}</button></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-b border-line pb-5"><div className="flex items-baseline gap-3"><span className="text-2xl font-semibold text-ink">{formatMoney(variant.price, locale)}</span>{product.comparisonPrice && <span className="text-sm text-muted line-through">{formatMoney(product.comparisonPrice, locale)}</span>}</div><span className={`rounded-full border px-3 py-1.5 text-[9px] font-bold uppercase tracking-[.13em] ${variant.stock > 0 ? 'border-accent/35 bg-[#FBF4E7] text-[#765116]' : 'border-line bg-[#F4F1EE] text-muted'}`}>{variant.stock > 0 ? `${variant.stock <= 5 ? t('lowStock') : t('inStock')} · ${variant.sku}` : t('outOfStock')}</span></div><p className="py-5 text-[15px] leading-7 text-muted sm:text-base">{product.shortDescription}</p>
      <div className="border-t border-line pt-5"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-ink">{copy.selectFinish}</span><div className="mt-3 grid gap-2 sm:grid-cols-2">{product.variants.map((item) => <button key={item.id} type="button" disabled={item.stock === 0} onClick={() => { setVariantId(item.id); setQuantity(1) }} className={`rounded-xl border px-4 py-3.5 text-left text-xs font-semibold transition duration-300 ${item.id === variant.id ? 'border-[#2F2A2C] bg-[#2F2A2C] text-white shadow-[0_10px_24px_rgba(47,42,44,.13)]' : 'border-line bg-white hover:border-accent hover:bg-[#FFFCF7]'} disabled:cursor-not-allowed disabled:opacity-40`}>{item.name}<span className="mt-1 block text-[10px] font-normal opacity-65">{formatMoney(item.price, locale)}</span></button>)}</div></div>
      <div className="mt-6 rounded-2xl border border-line bg-[#FBFAF8] p-3 sm:p-4"><div className="mb-3 flex items-center justify-between gap-4"><span className="text-[9px] font-bold uppercase tracking-[.16em] text-muted">{copy.quantity}</span><div className="flex h-11 items-center rounded-xl border border-line bg-white"><button type="button" className="grid h-full w-10 place-items-center transition-colors hover:text-accent" onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Decrease quantity"><Minus size={14} /></button><span className="w-8 text-center text-sm font-semibold">{quantity}</span><button type="button" className="grid h-full w-10 place-items-center transition-colors hover:text-accent" onClick={() => setQuantity(Math.min(variant.stock, quantity + 1))} aria-label="Increase quantity"><Plus size={14} /></button></div></div><button type="button" onClick={orderDirectly} disabled={variant.stock === 0} className="inline-flex min-h-[52px] w-full items-center justify-center gap-2.5 rounded-xl bg-[#C4953D] px-5 py-4 text-[10px] font-bold uppercase tracking-[.12em] text-[#241F21] shadow-[0_12px_28px_rgba(196,149,61,.22)] transition duration-300 hover:-translate-y-0.5 hover:bg-[#B88833] hover:shadow-[0_16px_34px_rgba(196,149,61,.3)] disabled:cursor-not-allowed disabled:bg-[#E8E1D9] disabled:text-[#8B7E80] disabled:shadow-none"><MessageCircle size={17} aria-hidden="true" />{copy.directOrder}</button><button type="button" onClick={add} disabled={variant.stock === 0} className="mt-2.5 inline-flex min-h-12 w-full items-center justify-center gap-2.5 rounded-xl border border-[#2F2A2C] bg-[#2F2A2C] px-5 text-[10px] font-bold uppercase tracking-[.11em] text-white transition duration-300 hover:bg-[#40393C] disabled:cursor-not-allowed disabled:border-line disabled:bg-[#E8E1D9] disabled:text-[#8B7E80]">{added ? <><Check size={16} />{copy.added}</> : <><ShoppingBag size={16} />{t('addToCart')}</>}</button></div>
      <div className="mt-7 divide-y divide-line border-y border-line text-sm"><details className="group py-1" open><summary className="flex cursor-pointer list-none items-center justify-between py-4 font-semibold [&::-webkit-details-marker]:hidden">{copy.description}<ChevronDown size={16} className="text-accent transition-transform group-open:rotate-180" /></summary><p className="pb-5 leading-7 text-muted">{product.description}</p></details><details className="group py-1"><summary className="flex cursor-pointer list-none items-center justify-between py-4 font-semibold [&::-webkit-details-marker]:hidden">{copy.specifications}<ChevronDown size={16} className="text-accent transition-transform group-open:rotate-180" /></summary><dl className="space-y-3 pb-5">{Object.entries(product.specifications).map(([key, value]) => <div key={key} className="flex justify-between gap-4 text-muted"><dt>{key}</dt><dd className="text-right font-medium text-ink">{value}</dd></div>)}</dl></details><details className="group py-1"><summary className="flex cursor-pointer list-none items-center justify-between py-4 font-semibold [&::-webkit-details-marker]:hidden">{copy.delivery}<ChevronDown size={16} className="text-accent transition-transform group-open:rotate-180" /></summary><p className="pb-5 leading-7 text-muted">{copy.deliveryBody}</p></details></div>
    </aside></section>
    <div role="region" aria-label={locale === 'fr' ? 'Actions d’achat sur mobile' : 'إجراءات الشراء على الهاتف'} className="fixed inset-x-0 bottom-[calc(64px+env(safe-area-inset-bottom))] z-30 flex min-h-[72px] items-center gap-2 border-t border-line bg-white/95 px-3 py-2 shadow-[0_-12px_34px_rgba(47,42,44,.12)] backdrop-blur-md md:hidden"><div className="min-w-0 flex-1"><p className="truncate text-[9px] font-bold uppercase tracking-[.12em] text-muted">{product.name}</p><p className="mt-1 text-sm font-semibold text-ink">{formatMoney(variant.price, locale)}</p></div><button type="button" onClick={add} disabled={variant.stock === 0} className="grid h-12 w-12 shrink-0 place-items-center rounded-xl border border-[#2F2A2C] bg-white text-[#2F2A2C] disabled:cursor-not-allowed disabled:opacity-40" aria-label={t('addToCart')}>{added ? <Check size={17} /> : <ShoppingBag size={17} />}</button><button type="button" onClick={orderDirectly} disabled={variant.stock === 0} aria-label={copy.directOrder} className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-[#C4953D] px-3 text-[9px] font-bold uppercase tracking-[.09em] text-[#241F21] shadow-[0_8px_22px_rgba(196,149,61,.22)] disabled:cursor-not-allowed disabled:bg-[#E8E1D9] disabled:text-[#8B7E80]"><MessageCircle size={16} aria-hidden="true" /><span className="hidden min-[390px]:inline">{copy.directOrder}</span><span className="min-[390px]:hidden">{locale === 'fr' ? 'Commander' : 'اطلبي'}</span></button></div>
    <section className="border-t border-line bg-white py-12 lg:py-16"><div className="container-shell"><p className="eyebrow">{copy.related}</p><h2 className="display mt-2 text-4xl font-semibold">{copy.relatedTitle}</h2><div className="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4 lg:gap-5">{products.filter((item) => item.id !== product.id).slice(0, 4).map((item) => <ProductCard key={item.id} product={item} />)}</div></div></section>
  </main>
}
